# sweet names and cost
sweets:
  _0:
    name: "Mentos"
    kost: 2
  _1:
    name: "Duplo"
    kost: 2
  _2:
    name: "Kinder"
    kost: 2
  _3:
    name: "Mauam"
    kost: 2
  _4:
    name: "Smarties"
    kost: 2
  _5:
    name: "Haribo"
    kost: 2
  _6:
    name: "Brause"
    kost: 2
  _7:
    name: "Stats"
    kost: -1
# time it takes for a login to be invalidated
invalidation-time: 14
website-url: "http://127.0.0.1:8080"
dispenser-url: "http://192.168.188.202"
scanner-url: "http://192.168.188.201"
station-url: "http://192.168.188.203"
default-logout-time: 10
window-dimension:
  horizontal: 480
  vertical: 800
shutdown-delay: 30
